apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import register_request, logout_request, login_request
app_name = 'accounts'
urlpatterns = [
    path("register/", register_request, name="register"),
    path("login/", login_request, name="login"),
    path("logout/", logout_request, name="logout"),
]

apps/catalog/urls.py
from django.urls import path, include

from apps.catalog.views import (access_denied,
                                products_by_cat_uid,
                                product_detail_by_uid,
                                product_create,
                                category_create,
                                search_results,
                                product_edit,
                                category_list)

app_name = 'catalog'

urlpatterns = [
    path('', category_list, name='category_list'),
    path('access_denied/', access_denied, name='access_denied'),
    path('search/', search_results, name='search_results'),
    path('create_category/', category_create, name='category_create'),
    path('detail/<str:prod_uid>/', product_detail_by_uid, name='product_detail'),
    path('product_edit/<str:prod_uid>/', product_edit, name='product_edit'),
    path('<str:cat_uid>/', products_by_cat_uid, name='product_list'),
    path('<str:cat_uid>/create/', product_create, name='product_create'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Django catalog{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
</head>

<body>

    <div class="site-wrap">
        {% include 'base/navbar.html' %}
            <div class="container">
              <div class="row">
                    <div class="col-4">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>

    </div>
</body>
</html>

templates/base/navbar.html
   <header class="site-navbar" role="banner">
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">
                    {% if user.is_authenticated %}
                        <form action="{% url 'catalog:search_results' %}" method="get">
                          <input name="q" type="text" placeholder="Search...">
                        </form>
                        <h5>{{ user.username }}</h5>
                        <a href="{% url 'accounts:logout' %}">LogOut</a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}">Login</a>
                        <a href="{% url 'accounts:register' %}">Register</a>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>