apps/catalog/urls.py
from django.urls import path, include

from apps.catalog.views import (access_denied,
                                products_by_cat_uid,
                                product_detail_by_uid,
                                product_create,
                                category_create,
                                search_results,
                                product_edit,
                                category_list)

app_name = 'catalog'

urlpatterns = [
    path('', category_list, name='category_list'),
    path('access_denied/', access_denied, name='access_denied'),
    path('search/', search_results, name='search_results'),
    path('create_category/', category_create, name='category_create'),
    path('detail/<str:prod_uid>/', product_detail_by_uid, name='product_detail'),
    path('product_edit/<str:prod_uid>/', product_edit, name='product_edit'),
    path('<str:cat_uid>/', products_by_cat_uid, name='product_list'),
    path('<str:cat_uid>/create/', product_create, name='product_create'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/catalog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from .mixins import IsActiveModel, UidPrimaryModel, TimeStampedModel

User = get_user_model()


class Category(IsActiveModel, UidPrimaryModel, TimeStampedModel):
    title = models.CharField(verbose_name="Название категории",
                             max_length=50,
                             null=False,
                             blank=False)
    manager = models.ForeignKey(to=User, on_delete=models.PROTECT, default=None)

    def __str__(self):
        return self.title


class Product(IsActiveModel, UidPrimaryModel, TimeStampedModel):
    title = models.CharField(verbose_name="Название товара",
                             max_length=50,
                             null=False,
                             blank=False)

    category = models.ForeignKey(to=Category,
                                 on_delete=models.DO_NOTHING)
    article = models.CharField('Артикул', max_length=250, db_index=True)
    description = models.TextField('Описание')
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    available = models.BooleanField('Наличие товара', default=True)

    def __str__(self):
        return self.title

apps/catalog/forms.py
from django import forms

from apps.catalog.models import Product, Category


class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['title', 'manager']


class ProductCreateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'category']

apps/catalog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from apps.catalog.forms import ProductCreateForm, CategoryCreateForm
from apps.catalog.models import Category, Product
from apps.catalog.permissions import check_category_manager, check_product_manager

User = get_user_model()


@login_required
def category_list(request, *args, **kwargs):
    user = User.objects.get(username=request.user.username)
    if user.is_staff:
        categories = Category.objects.all()
        context = {'categories': categories,
                   'user': request.user}
    elif user.is_manager:
        user = User.objects.get(username=request.user.username)
        categories = Category.objects.filter(is_active=True, manager=user)
        context = {'categories': categories,
                   'user': request.user}
    else:
        context = {'user': request.user}
    return render(request, 'catalog/category-list.html', context)


@login_required
@check_category_manager
def products_by_cat_uid(request, cat_uid):
    category = Category.objects.get(uid=cat_uid)
    products = Product.objects.filter(category=category)
    context = {'products': products,
               'category': category}
    return render(request, 'catalog/product-list.html', context)


@login_required
@check_product_manager
def product_detail_by_uid(request, prod_uid):
    product = Product.objects.get(uid=prod_uid)
    context = {'product': product}
    return render(request, 'catalog/product-detail.html', context)


@login_required
@check_category_manager
def product_create(request, cat_uid):
    category = Category.objects.get(uid=cat_uid)

    if request.method == 'POST':
        form = ProductCreateForm(request.POST)
        if form.is_valid():
            product = Product()
            product.title = form.cleaned_data['title']
            product.description = form.cleaned_data['description']
            product.price = form.cleaned_data['price']
            product.category = category
            product.save()
            return redirect("catalog:category_list")
    else:
        form = ProductCreateForm()
        context = {'category': category,
                   'product_form': form}
        return render(request, 'catalog/product-create.html', context)


@login_required
def category_create(request):
    if request.method == 'POST':
        form = CategoryCreateForm(request.POST)
        if form.is_valid():
            category = form.save()
            category.title = form.cleaned_data['title']
            category.save()
            return redirect("catalog:category_list")
    else:
        form = CategoryCreateForm()
        context = {'category_form': form}
        return render(request, 'catalog/category-create.html', context)


@login_required
def search_results(request):
    query = request.GET.get("q")
    or_lookup = (Q(title__icontains=query) | Q(description__icontains=query) | Q(price__icontains=query))

    products = Product.objects.filter(or_lookup)
    context = {'products': products}
    return render(request, 'catalog/search-results.html', context)


@login_required
@check_product_manager
def product_edit(request, prod_uid):
    product = get_object_or_404(Product, uid=prod_uid)

    if request.method == 'GET':
        form = ProductCreateForm(instance=product)

    if request.method == 'POST':
        form = ProductCreateForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
        return redirect('catalog:product_detail', prod_uid=prod_uid)

    return render(request, 'catalog/product_edit.html', {'product_form': form, 'product': product})


@login_required
def access_denied(request):
    return render(request, 'catalog/access-denied.html')

templates/catalog/access-denied.html
NO ACCESS
<a href="{% url 'catalog:category_list' %}">Categories</a>

templates/catalog/category-create.html
{% extends 'base/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Create new category</h1>
	<form method="POST">
		{% csrf_token %}
		{{ category_form|crispy }}
		<button class="btn btn-primary" type="submit">Create</button>
	</form>
</div>

{% endblock %}

templates/catalog/category-list.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
    {% if user.is_superuser %}
        <a href="{% url 'catalog:category_create' %}">Create new category</a>
    {% endif %}
    <ul>
        {% for cat in categories %}
            <li>
                <a href="{% url 'catalog:product_list' cat.uid %}">{{ cat.title }}</a>___<a href="{% url 'catalog:product_create' cat.uid%}">Create new product</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/catalog/product-create.html
{% extends 'base/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Create new product</h1>
	<form method="POST">
		{% csrf_token %}
		{{ product_form|crispy }}
		<button class="btn btn-primary" type="submit">Create</button>
	</form>
</div>

{% endblock %}

templates/catalog/product-detail.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Detail
{% endblock %}
   <h3>{{ product.title }}</h3>

{% block content %}
   <h3>{{ product.title }}</h3>
    <ul>
        <li>{{ product.description }}</li>
        <li>{{ product.price }}</li>
    </ul>
    <a href="{% url 'catalog:product_edit' product.uid %}">EDIT</a>
{% endblock %}

templates/catalog/product-list.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{{ category.name }}
{% block content %}
    <ul>
        {% for prod in products %}
            <li>
                <a href="{% url 'catalog:product_detail' prod.uid %}">{{ prod.title }}</a>___<a href="{% url 'catalog:product_edit' prod.uid%}">edit</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/catalog/product_edit.html
{% extends 'base/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Edit product</h1>
	<form method="POST">
		{% csrf_token %}
		{{ product_form|crispy }}
		<button class="btn btn-primary" type="submit">Save</button>
	</form>
</div>

{% endblock %}

templates/catalog/search-results.html
<h1>Search Results</h1>

<ul>
  {% for prod in products %}
    <li>
    <a href="{% url 'catalog:product_detail' prod.uid %}">{{ prod.title }}, {{ prod.price }}</a>
    </li>
  {% endfor %}
</ul>